[package]
name = "xzip-gui"
description = "xZip Archiver desktop app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "xzip-gui"
path = "src/main.rs"

[dependencies]
drag = "2.1.1"
eframe = { version = "0.36", default-features = false, features = ["glow", "default_fonts", "persistence", "x11", "wayland"] }
egui = "0.36"
egui-phosphor = "0.14.0"
egui_extras = "0.36"
image = "0.25.6"
rayon = "1.12.0"
rfd = "0.17.2"
xzip-core = { path = "../xzip-core" }

[build-dependencies]
winresource = "0.1.31"
